### ISSUE TITLE
Exception when running on Hadoop

### ISSUE THREAD

**Issue by deemp** [nikololiahim/polystat-cli#2]
I'm trying to run with these [commands](https://github.com/br4ch1st0chr0n3/polyscat#running-on-hadoop)
After hadoop is translated and polystat starts running, get this

```sh
[error] java.lang.Exception: ../j2eo_hadoop/hadoop-mapreduce-project/dev-support/jdiff/Null.eo: 
[error]         at org.polystat.Main$$anonfun$$nestedInanonfun$runPolystat$7$1.applyOrElse(Main.scala:93)
[error]         at org.polystat.Main$$anonfun$$nestedInanonfun$runPolystat$7$1.applyOrElse(Main.scala:93)
[error]         at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:288)
[error]         at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:130)
[error]         at flatMap @ org.polystat.odin.analysis.EOOdinAnalyzer$.analyzeSourceCode(EOOdinAnalyzer.scala:149)
[error]         at traverse @ org.polystat.Main$.analyze(Main.scala:55)
[error]         at traverse @ org.polystat.Main$.analyze(Main.scala:55)
[error]         at traverse @ org.polystat.Main$.analyze(Main.scala:55)
[error]         at adaptError$extension @ org.polystat.Main$.$anonfun$runPolystat$7(Main.scala:92)
[error]         at map @ org.polystat.Main$.$anonfun$runPolystat$7(Main.scala:92)
[error]         at flatMap @ org.polystat.Main$.$anonfun$runPolystat$7(Main.scala:92)
[error]         at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.createTempDirectory(FilesPlatform.scala:162)
[error]         at flatMap @ org.polystat.Main$.$anonfun$runPolystat$4(Main.scala:89)
[error] Caused by: java.lang.IllegalArgumentException: 
[error] :3:14: error: expected one of:
[error]     '\t'
[error]     ' '
[error] 3| +alias stdlib.class__Object
[error]   |              ^
[error]         at org.polystat.odin.parser.EoParser$$anon$1.$anonfun$parse$1(EoParser.scala:39)
[error]         at cats.syntax.EitherOps$.leftMap$extension(either.scala:172)
[error]         at org.polystat.odin.parser.EoParser$$anon$1.parse(EoParser.scala:39)
[error]         at org.polystat.odin.parser.EoParser$$anon$1.parse(EoParser.scala:30)
[error]         at org.polystat.odin.analysis.EOOdinAnalyzer$.analyzeSourceCode(EOOdinAnalyzer.scala:149)
[error]         at org.polystat.Main$.$anonfun$analyze$1(Main.scala:57)
[error]         at cats.data.Chain$.$anonfun$traverseViaChain$3(Chain.scala:795)
[error]         at cats.Eval$.loop$1(Eval.scala:317)
[error]         at cats.Eval$.cats$Eval$$evaluate(Eval.scala:363)
[error]         at cats.Eval$FlatMap.value(Eval.scala:284)
[error]         at cats.data.Chain$.traverseViaChain(Chain.scala:817)
[error]         at cats.instances.ListInstances$$anon$1.traverse(list.scala:100)
[error]         at cats.instances.ListInstances$$anon$1.traverse(list.scala:17)
[error]         at cats.Traverse$Ops.traverse(Traverse.scala:181)
[error]         at cats.Traverse$Ops.traverse$(Traverse.scala:180)
[error]         at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:206)
[error]         at org.polystat.Main$.analyze(Main.scala:55)
[error]         at org.polystat.Main$.$anonfun$runPolystat$7(Main.scala:92)
[error]         at flatMap @ org.polystat.odin.analysis.EOOdinAnalyzer$.analyzeSourceCode(EOOdinAnalyzer.scala:149)
[error]         at traverse @ org.polystat.Main$.analyze(Main.scala:55)
[error]         at traverse @ org.polystat.Main$.analyze(Main.scala:55)
[error]         at traverse @ org.polystat.Main$.analyze(Main.scala:55)
[error]         at adaptError$extension @ org.polystat.Main$.$anonfun$runPolystat$7(Main.scala:92)
[error]         at map @ org.polystat.Main$.$anonfun$runPolystat$7(Main.scala:92)
[error]         at flatMap @ org.polystat.Main$.$anonfun$runPolystat$7(Main.scala:92)
[error]         at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.createTempDirectory(FilesPlatform.scala:162)
[error]         at flatMap @ org.polystat.Main$.$anonfun$runPolystat$4(Main.scala:89)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) java.lang.Exception: ../j2eo_hadoop/hadoop-mapreduce-project/dev-support/jdiff/Null.eo: 
[error] Total time: 2 s, completed Apr 23, 2022, 6:30:47 PM
```

**Comment by deemp** [comment]
This was Odin problem
